name: "[DEBUG] Push Image Test with test.json"

on:
  workflow_dispatch:

env:
  DOCKERHUB_USERNAME: "pbranly"

jobs:
  test-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Vérifier variables
        run: |
          echo "DOCKERHUB_USERNAME = $DOCKERHUB_USERNAME"
          if [ -z "${{ secrets.DOCKERHUB_TOKEN }}" ]; then
            echo "❌ DOCKERHUB_TOKEN est vide"
            exit 1
          else
            echo "✅ DOCKERHUB_TOKEN est défini"
          fi

      - name: Login DockerHub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      - name: Créer test.json
        run: |
          echo '{"status":"ok","message":"connexion DockerHub réussie"}' > test.json
          cat test.json

      - name: Construire Dockerfile
        run: |
          echo "FROM alpine" > Dockerfile
          echo "COPY test.json /test.json" >> Dockerfile
          cat Dockerfile

      - name: Build image
        run: |
          docker build -t $DOCKERHUB_USERNAME/test-json:debug .

      - name: Push image vers DockerHub
        run: |
          docker push $DOCKERHUB_USERNAME/test-json:debug
