name: "[DEBUG] Test DockerHub Login"

on:
  workflow_dispatch:

env:
  DOCKERHUB_USERNAME: "pbranly"   # ⚠️ mettre ton login DockerHub ici en clair juste pour debug

jobs:
  test-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Vérifier les variables
        run: |
          echo "DOCKERHUB_USERNAME = $DOCKERHUB_USERNAME"
          if [ -z "${{ secrets.DOCKERHUB_TOKEN }}" ]; then
            echo "❌ DOCKERHUB_TOKEN est vide"
            exit 1
          else
            echo "✅ DOCKERHUB_TOKEN est défini (non affiché pour sécurité)"
          fi

      - name: Lancer login avec debug
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker --debug login -u "$DOCKERHUB_USERNAME" --password-stdin
