name: "[DEBUG] Test DockerHub Login + File"

on:
  workflow_dispatch:

env:
  DOCKERHUB_USERNAME: "pbranly"   # ⚠️ ton login en clair, juste pour debug

jobs:
  test-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Vérifier les variables
        run: |
          echo "DOCKERHUB_USERNAME = $DOCKERHUB_USERNAME"
          if [ -z "${{ secrets.DOCKERHUB_TOKEN }}" ]; then
            echo "❌ DOCKERHUB_TOKEN est vide"
            exit 1
          else
            echo "✅ DOCKERHUB_TOKEN est défini (non affiché pour sécurité)"
          fi

      - name: Login DockerHub avec debug
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker --debug login -u "$DOCKERHUB_USERNAME" --password-stdin

      - name: Créer un fichier test.json dans un conteneur
        run: |
          echo '{"status":"ok","message":"connexion DockerHub réussie"}' > test.json
          echo "👉 Contenu local de test.json :"
          cat test.json

          echo "👉 Lancer un conteneur et copier test.json dedans..."
          docker run --name test-container -d alpine sleep 60
          docker cp test.json test-container:/test.json

          echo "👉 Lire test.json dans le conteneur :"
          docker exec test-container cat /test.json

          # Nettoyage
          docker rm -f test-container
