name: "[DEBUG] Test DockerHub Login"

on:
  workflow_dispatch:

jobs:
  test-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Afficher les secrets utilisés (sauf token)
        run: |
          echo "DOCKERHUB_USERNAME = ${{ secrets.DOCKERHUB_USERNAME }}"
          if [ -z "${{ secrets.DOCKERHUB_TOKEN }}" ]; then
            echo "❌ DOCKERHUB_TOKEN est vide"
            exit 1
          else
            echo "✅ DOCKERHUB_TOKEN est défini (non affiché pour sécurité)"
          fi

      - name: Afficher la commande login (sans exécution)
        run: |
          echo "👉 La commande qui serait exécutée est :"
          echo "echo <DOCKERHUB_TOKEN> | docker login -u '${{ secrets.DOCKERHUB_USERNAME }}' --password-stdin"

      - name: Exécuter le login DockerHub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
